name: CI & Test Streamlit + Playwright

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers & OS deps
        run: |
          # this pulls down Chromium, Firefox, WebKit
          playwright install --with-deps

      # Optional: run any unit tests you have
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      # Smoke-test your Streamlit app in headless mode
      - name: Smoke-test Streamlit startup
        run: |
          # run in background
          nohup streamlit run streamlit_app.py --server.headless true --server.port 8501 &
          sleep 10
          # check that it’s listening
          if ! curl -sf http://localhost:8501; then
            echo "Streamlit did not start properly" >&2
            exit 1
          fi
